AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PostsTable:
   Type: AWS::Serverless::SimpleTable
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Timeout: 10
      Environment:
       Variables:
         TABLE_NAME: !Ref PostsTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY

Globals:
 Api:
   Cors:
     AllowMethods: "'*'"
     AllowHeaders: "'*'"
     AllowOrigin: "'*'"
 Function:
    Runtime: nodejs12.x